### PR TITLE
Project improve

### PR DESCRIPTION
**Pull request by Soullivaneuh**
- [x] Travis config improve (see commit comment)
- [x] ~~Fix tests and requirements if needed~~
- [x] Configure CS fixer
- [x] Apply CS fixer

Note: You have to set up a Github token on secure `GITHUB_OAUTH_TOKEN` Travis env var. This token need no special permissions and will not appears on PR.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@henrikbjorn @ornicar Travis seems not to be fully configured: https://travis-ci.org/ornicar/GravatarBundle

Could you take a look?

**Comment by Soullivaneuh** [comment]
CS diff could be find on this commit with resume on comment: b225852badc3e91666d54c4f8b956628cf121a98

**Comment by ornicar** [comment]
This project is not maintained. Feel free to fork.

**Comment by Soullivaneuh** [comment]
I'm sorry but why https://github.com/ornicar/GravatarBundle/pull/35 was merged by @henrikbjorn is it's not maintained?

Adding collaborator or transfer it on a group would not be better than a fork?

Thanks.

**Comment by Soullivaneuh** [comment]
And BTW, if this is really unmaintened, you should mark it on the README. :+1:

**Comment by ornicar** [comment]
Ah ok, perhaps @henrikbjorn will handle this, then.

**Comment by Soullivaneuh** [comment]
@ornicar Can you so please reopen this PR? Thanks.

If you don't want to maintain it anymore, maybe you could transfert ownership to @henrikbjorn or somebody else.

He is actually stuck for some issue like #33.

**Comment by henrikbjorn** [comment]
I think instead of using phpcs directly we should use Scrutinizer.

**Comment by henrikbjorn** [comment]
@ornicar If you can transfer owner ship or similiar, i would be happy to merge stuff.

**Comment by Soullivaneuh** [comment]
> I think instead of using phpcs directly we should use Scrutinizer.

This is not the same. With php-cs, we will be sure to follows completly Symfony standards rules.

And in addition, this provide a quick tools for contributors who want to fix CS. Just run `make cs` and you are done.

Scrutinizer could find other things that could be improved later. I think both should be used.

I use both of them for my project. See sample: https://github.com/Soullivaneuh/IsoCodesValidator/pull/28

**Comment by Spomky** [comment]
Hi everybody,

I just want to share with you the tools I usually enable for my projects.

* [Scrutinizer](https://scrutinizer-ci.com/). It provides very good features such as dead code and bugs detection and code mertics.
* Same goes for [Insight](https://insight.sensiolabs.com), but it detects also bad practices, especially concerning Symfony bundles.
* Continuous testing with [Travis-CI](https://travis-ci.org/). I see you already enabled it, but:
    * If tests are performed by PHPUnit and you use Scrutinizer, you also should enable code coverage in your Travis-CI configuration. Scrutinizer will provide you better reports.
* As coding strandards matter,  [StyleCI](https://styleci.io/) will provides you an easy way to fix your code.

Do not forget to add badges. It is not just for design. Take a look at [one of my projects](https://github.com/Spomky-Labs/aes-key-wrap) to see how it could be useful for you.

**Comment by henrikbjorn** [comment]
@Spomky Scrutinizer does also check for PSR style usage, dead code etc. I would rather have an external tool instead of littlering the project code with phpcs, even though i like your initiative!

Regarding badges. I am going to add the Travis one, the others i dont see the purpose and i dont really like the trend of having all those badges.

**Comment by Soullivaneuh** [comment]
> Scrutinizer does also check for PSR style usage.

Yes, but two point missing IMO:

* No Symfony codint style rules
* Do not force user to correct it on PR (failing test). The proof is here, lot of code changed with php-cs. :+1:

**Comment by Soullivaneuh** [comment]
ping @henrikbjorn

**Comment by henrikbjorn** [comment]
I have set up scrutinizer for the repository with php-cs-fixer and psr2 level.

https://scrutinizer-ci.com/g/henrikbjorn/GravatarBundle/issues/master

If you remove php-cs-fixer integration from this pr, ill merge it.

**Comment by Soullivaneuh** [comment]
@henrikbjorn Set up Scrutinizer is a good idea but I think CS fixer should be on Travis too.

Scrutinizer will not necessarly block PR if CS is not respected, Travis will.

**Comment by henrikbjorn** [comment]
phpcsfixer will not be on travis. Scrutinizer will inspect Pull Request.

Adding this https://scrutinizer-ci.com/docs/configuration/build_status will mark inspections with violations as failed.

**Comment by Soullivaneuh** [comment]
@henrikbjorn done.

**Comment by henrikbjorn** [comment]
Thanks for your work on this.

**Pull request merged**
