### PR TITLE
Add support for Symfony 4.0

### PR DESCRIPTION
**Pull request by tehplague**
Let's add support for Symfony 4.0 which has been released today.

### CODE REVIEW

**Comment by nicoschoenmaker** [comment]
Tried this pull request in a Symfony 4 app, works just fine. I guess no deprecated features were used :slightly_smiling_face:

@henrikbjorn do you have time to look at this PR? It's currently holding back the upgrade to Symfony 4  in several apps for us.

**Comment by henrikbjorn** [comment]
Ill merge when the tests are green :)

**Comment by nicoschoenmaker** [comment]
Fair enough, see #54 for some nice green lights from travis

**Comment by henrikbjorn** [comment]
needs rebase, good work :D

**Comment by nicoschoenmaker** [comment]
This commit was also cherry-picked to #54, so I guess this guy and #51 can be closed!

**Comment by nicoschoenmaker** [comment]
@henrikbjorn would it be possible to tag this in a release? That way we can avoid following this package on `dev-master`, and the instabilities that tend to go with that.

**Pull request closed without merging**
