### PR TITLE
Add cache layer

### PR DESCRIPTION
**Pull request by ZhukV**
Adds cache layer to system, because if i use exist in each page, then system send http requests to Gravatar. All system now works, i create a BC for all systems.

And, must:
1. Mask `GravatarApi` as **deprecated**, and remove in next versions.
2. Add another cache layer (redis, memcached, etc...)

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Cool. I like the caching idea, but we should use an existing library, such as Doctrine :)

**Comment by ZhukV** [comment]
So, i not use a common libraries (Doctrine cache, or another), because the many systems creates without this libraries (as example, in my projects i not use doctrine cache system). If developer want use any caching system (Doctrine Cache as example), then he create a custom cache adapter and implement `Cache\CacheInterface` interface and after configure.

```yaml
ornicar_gravatar:
    secure: true
    cache: my_custom_cache.service_id
```

As solution, we can add another cache adapters.

**Comment by ZhukV** [comment]
ping?!!

**Comment by jm42** [comment]
What about [PSR-6](http://www.php-fig.org/psr/psr-6/)?

**Comment by Soullivaneuh** [comment]
Also since SF 3.1, a native cache system is provided, based on PSR-6: https://symfony.com/blog/new-in-symfony-3-1-cache-component

**Comment by henrikbjorn** [comment]
I vote in favor or the cache component in Symfony

**Pull request closed without merging**
